WebPasajero/Models/Pasajero.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace WebPasajero.Models
{
    public class Pasajero
    {
        public int PasajeroId { get; set; }

        [Display(Name = "Nombre")]
        public string Nombre { get; set; }

        [Display(Name = "Apellido")]
        public string Apellido { get; set; }

        public string Ciudad { get; set; }
        public int FechaNacimiento { get; set; }
    }
}

WebPasajero/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebPasajero.Models;

namespace WebPasajero.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

       
    }
}

WebPasajero/Controllers/PasajeroController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System;
using WebPasajero.Data;
using WebPasajero.Models;
using System.Linq;

namespace WebPasajero.Controllers
{
    public class PasajeroController : Controller
    {
        private readonly PasajeroContext _context;

        public PasajeroController(PasajeroContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View(_context.Pasajeros.ToList());
        }

        [HttpGet("/pasajero/ListaPorCiudad/{city}")]
        public IActionResult ListaPorCiudad(string city)
        {
            List<Pasajero> lista = (from p in _context.Pasajeros
                                  where p.Ciudad == city
                                  select p).ToList();
            return View("index", lista);
        }


        public IActionResult Edit(int id)
        {
            var pasajero = _context.Pasajeros.SingleOrDefault(m => m.PasajeroId == id);
            pasajero.Nombre = "Brandon";
            _context.Update(pasajero);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Create()
        {
            Pasajero pasajero = new Pasajero();
            return View("Create", pasajero);
        }

        // POST: /Person/Create
        [HttpPost]
        public IActionResult Create(Pasajero pasajero)
        {
            _context.Add(pasajero);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }


        public IActionResult Delete(int id)
        {
            var pasajero = _context.Pasajeros.SingleOrDefault(m => m.PasajeroId == id);
            _context.Pasajeros.Remove(pasajero);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

WebPasajero/Views/Home/Index.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
 <a asp-action="Index" asp-controller="Pasajero" >Pasajero</a>
@Html.ActionLink("Ir a Pasajero","Index","Pasajero")

 pasajero","Index");

WebPasajero/Views/Pasajero/Create.cshtml
@model WebPasajero.Models.Pasajero
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    <h4>Pasajero</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Nombre" class="control-label"></label>
                    <input asp-for="Nombre" class="form-control" />
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Apellido" class="control-label"></label>
                    <input asp-for="Apellido" class="form-control" />
                    <span asp-validation-for="Apellido" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Ciudad" class="control-label"></label>
                    <input asp-for="Ciudad" class="form-control" />
                    <span asp-validation-for="Ciudad" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="FechaNacimiento" class="control-label"></label>
                    <input asp-for="FechaNacimiento" class="form-control" />
                    <span asp-validation-for="FechaNacimiento" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>

</body>
</html>

WebPasajero/Views/Pasajero/Index.cshtml
@model IEnumerable<WebPasajero.Models.Pasajero>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>

    <p>
        @Html.ActionLink("Nuevo Pasajero", "Create", "Pasajero")
    </p>

    <table>
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Nombre)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Apellido)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Ciudad)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FechaNacimiento)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nombre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Apellido)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Ciudad)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FechaNacimiento)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.PasajeroId">Edit</a> |
                        <a asp-action="Delete" asp-route-id="@item.PasajeroId">Delete</a>
                        <a asp-action="Create" asp-controller="Pasajero">Nuevo Pasajero</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</body>
</html>

WebPasajero/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/css/site.css" rel="stylesheet" />
</head>
<body>
    <main>
        <div class="menu">

            <h3>Menu</h3>
        </div>
        <div class="container">
            <div class="header">
                <h3>Header</h3>
            </div>
            <div class="contentMain">
                <div class="content">
                    <h3>Content</h3>
                    @RenderBody()
                </div>
                <div class="sideBar">
                    @if (IsSectionDefined("sideBar"))
                    {
                        @RenderSection("sideBar")
                    }
                    else
                    {
                        <h2>Zona Sidebar</h2>
                    }

                </div>
            </div>
        </div>
    </main>

</body>
</html>